GET http://52.79.251.171:8000/api/categories/67a8348842292bc9d55aebfe/memos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTgzNDg4NDIyOTJiYzlkNTVhZWJmYyIsImVtYWlsIjoidXNlckBzYW1wbGUuY29tIiwiaWF0IjoxNzM5MDc2NzQ1LCJleHAiOjE3NDE2Njg3NDV9.Z_qVPlAi6W9Y8M7BbHHMfywarhronSLbuUpK8ja3Qlc

###

GET http://52.79.251.171:8000/api/categories/67a8348842292bc9d55aebfc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3YTgzNDg4NDIyOTJiYzlkNTVhZWJmYyIsImVtYWlsIjoidXNlckBzYW1wbGUuY29tIiwiaWF0IjoxNzM5MDc2NzQ1LCJleHAiOjE3NDE2Njg3NDV9.Z_qVPlAi6W9Y8M7BbHHMfywarhronSLbuUpK8ja3Qlc
