import './globals.css';
import StyledComponentsRegistry from '../registry';
import Providers from './providers'; // ✅ 클라이언트 Provider 불러오기
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Toast-it',
  description: 'Generated by Toast-it',
  icons: {
    icon: '/favicon/favicon.svg',
  },
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* ✅ SUIT 폰트 CDN을 head 태그에 추가 */}
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/sun-typeface/SUIT@2/fonts/variable/woff2/SUIT-Variable.css"
        />
      </head>
      <body
        style={{
          position: 'absolute',
          top: '0' /* 💡 최상단 배치 */,
          left: '0',
          width: '100vw', // 💡 화면 전체를 차지하도록 설정
          height: '100vh',
          paddingTop: 'env(safe-area-inset-top, 0px)' /* 💡 iOS 안전 영역 반영 */,
          margin: '0',
          display: 'flex',
          justifyContent: 'center', // 💡 중앙 정렬
          alignItems: 'center', // 💡 중앙 정렬
          backgroundColor: '#E5DCCA',
          overflow: 'hidden',
          fontFamily: `SUIT Variable, Apple SD Gothic Neo, sans-serif`, // ✅ 글로벌 폰트 적용
        }}
      >
        <StyledComponentsRegistry>
          <Providers>
            <div
              style={{
                width: '375px', // 아이폰 13 미니 너비
                height: '100dvh', // 아이폰 13 미니 높이
                position: 'absolute', // 💡 중앙 정렬을 위해 absolute 사용
                top: '50%',
                left: '50%',
                transform: 'translate(-50%, -50%)', // 💡 중앙 정렬 유지
                boxShadow: '0 0 10px rgba(0, 0, 0, 0.1)', // 💡 입체감 추가
                display: 'flex',
                flexDirection: 'column',
                backgroundColor: '#171612', // 💡 앱 배경색 추가
                overflow: 'hidden',
                fontFamily: `'SUIT Variable', sans-serif`, // ✅ 앱 전체에 폰트 적용
              }}
            >
              {children}
            </div>
          </Providers>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
