import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Toast-it',
  description: 'Generated by Toast-it',
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
};
